// desktop/frontend/src/app/components/operations-tree/operation-settings-panel.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SyncConfig } from '../../models/flow.model';
import { NeoButtonComponent } from '../neo/neo-button.component';
import { NeoInputComponent } from '../neo/neo-input.component';
import { NeoToggleComponent } from '../neo/neo-toggle.component';
import { NeoDropdownComponent, DropdownOption } from '../neo/neo-dropdown.component';

@Component({
  selector: 'app-operation-settings-panel',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NeoButtonComponent,
    NeoInputComponent,
    NeoToggleComponent,
    NeoDropdownComponent,
  ],
  template: `
    <div class="border-t-2 border-sys-border bg-sys-bg p-4 space-y-4" [class.opacity-50]="disabled" [class.pointer-events-none]="disabled">
      <!-- Action Type & Dry Run -->
      <div class="grid grid-cols-2 gap-4">
        <div>
          <span class="block text-sm font-bold mb-1">Action</span>
          <neo-dropdown
            [options]="actionOptions"
            [fullWidth]="true"
            [(ngModel)]="config.action"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-dropdown>
        </div>
        <div>
          <span class="block text-sm font-bold mb-1">Dry Run</span>
          <neo-toggle
            [(ngModel)]="config.dryRun"
            (ngModelChange)="onConfigChange()"
            label="Preview only"
            [disabled]="disabled"
          ></neo-toggle>
        </div>
      </div>

      <!-- Performance -->
      <div>
        <h3 class="text-sm font-bold mb-2 flex items-center gap-2">
          <i class="pi pi-bolt"></i> Performance
        </h3>
        <div class="grid grid-cols-2 gap-3">
          <neo-input
            label="Parallel"
            type="number"
            placeholder="8"
            [(ngModel)]="config.parallel"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
          <neo-input
            label="Bandwidth (MB/s)"
            type="number"
            placeholder="0 (unlimited)"
            [(ngModel)]="config.bandwidth"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
        </div>
        <details class="mt-2">
          <summary class="text-xs text-sys-text-secondary cursor-pointer select-none hover:text-sys-text">Advanced Performance</summary>
          <div class="grid grid-cols-2 gap-3 mt-2">
            <neo-input
              label="Multi-thread Streams"
              type="number"
              placeholder="4"
              [(ngModel)]="config.multiThreadStreams"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Buffer Size"
              placeholder="16M"
              [(ngModel)]="config.bufferSize"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Retries"
              type="number"
              placeholder="3"
              [(ngModel)]="config.retries"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Low-level Retries"
              type="number"
              placeholder="10"
              [(ngModel)]="config.lowLevelRetries"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Max Duration"
              placeholder="e.g. 1h30m"
              [(ngModel)]="config.maxDuration"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Retries Sleep"
              placeholder="e.g. 10s"
              [(ngModel)]="config.retriesSleep"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="TPS Limit"
              type="number"
              placeholder="0 (unlimited)"
              [(ngModel)]="config.tpsLimit"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Connect Timeout"
              placeholder="e.g. 30s"
              [(ngModel)]="config.connTimeout"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="IO Timeout"
              placeholder="e.g. 5m"
              [(ngModel)]="config.ioTimeout"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Order By"
              placeholder="e.g. size,desc"
              [(ngModel)]="config.orderBy"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
          </div>
          <div class="grid grid-cols-2 gap-3 mt-2">
            <neo-toggle
              [(ngModel)]="config.fastList"
              (ngModelChange)="onConfigChange()"
              label="Fast List"
              [disabled]="disabled"
            ></neo-toggle>
            <neo-toggle
              [(ngModel)]="config.checkFirst"
              (ngModelChange)="onConfigChange()"
              label="Check First"
              [disabled]="disabled"
            ></neo-toggle>
          </div>
        </details>
      </div>

      <!-- Filtering -->
      <div>
        <h3 class="text-sm font-bold mb-2 flex items-center gap-2">
          <i class="pi pi-filter"></i> Filtering
        </h3>
        <div class="grid grid-cols-2 gap-3">
          <label class="block">
            <span class="block text-sm font-medium mb-1">Include Paths</span>
            <textarea
              class="w-full px-3 py-2 border-2 border-sys-border shadow-neo-sm font-mono text-sm resize-none"
              rows="3"
              placeholder="/path/to/include&#10;/another/path"
              [ngModel]="includedPathsText"
              (ngModelChange)="updateIncludedPaths($event)"
              [disabled]="disabled"
            ></textarea>
          </label>
          <label class="block">
            <span class="block text-sm font-medium mb-1">Exclude Paths</span>
            <textarea
              class="w-full px-3 py-2 border-2 border-sys-border shadow-neo-sm font-mono text-sm resize-none"
              rows="3"
              placeholder="*.tmp&#10;node_modules/"
              [ngModel]="excludedPathsText"
              (ngModelChange)="updateExcludedPaths($event)"
              [disabled]="disabled"
            ></textarea>
          </label>
        </div>
        <details class="mt-2">
          <summary class="text-xs text-sys-text-secondary cursor-pointer select-none hover:text-sys-text">Advanced Filtering</summary>
          <div class="grid grid-cols-2 gap-3 mt-2">
            <!-- Min Size: number + unit -->
            <div>
              <span class="block text-sm font-medium mb-1">Min Size</span>
              <div class="flex gap-1">
                <input
                  type="number"
                  min="0"
                  class="flex-1 w-0 px-3 py-2 bg-sys-bg border-2 border-sys-border shadow-neo-sm font-medium text-sm placeholder:text-sys-fg-tertiary focus:outline-none focus:ring-2 focus:ring-sys-accent-secondary disabled:opacity-50"
                  placeholder="0"
                  [(ngModel)]="minSizeNum"
                  (ngModelChange)="onSizeFieldChange('minSize')"
                  [disabled]="disabled"
                />
                <neo-dropdown
                  [options]="sizeUnitOptions"
                  [(ngModel)]="minSizeUnit"
                  (ngModelChange)="onSizeFieldChange('minSize')"
                  [disabled]="disabled"
                ></neo-dropdown>
              </div>
            </div>
            <!-- Max Size: number + unit -->
            <div>
              <span class="block text-sm font-medium mb-1">Max Size</span>
              <div class="flex gap-1">
                <input
                  type="number"
                  min="0"
                  class="flex-1 w-0 px-3 py-2 bg-sys-bg border-2 border-sys-border shadow-neo-sm font-medium text-sm placeholder:text-sys-fg-tertiary focus:outline-none focus:ring-2 focus:ring-sys-accent-secondary disabled:opacity-50"
                  placeholder="0"
                  [(ngModel)]="maxSizeNum"
                  (ngModelChange)="onSizeFieldChange('maxSize')"
                  [disabled]="disabled"
                />
                <neo-dropdown
                  [options]="sizeUnitOptions"
                  [(ngModel)]="maxSizeUnit"
                  (ngModelChange)="onSizeFieldChange('maxSize')"
                  [disabled]="disabled"
                ></neo-dropdown>
              </div>
            </div>
            <!-- Max Age: number + unit -->
            <div>
              <span class="block text-sm font-medium mb-1">Max Age</span>
              <div class="flex gap-1">
                <input
                  type="number"
                  min="0"
                  class="flex-1 w-0 px-3 py-2 bg-sys-bg border-2 border-sys-border shadow-neo-sm font-medium text-sm placeholder:text-sys-fg-tertiary focus:outline-none focus:ring-2 focus:ring-sys-accent-secondary disabled:opacity-50"
                  placeholder="0"
                  [(ngModel)]="maxAgeNum"
                  (ngModelChange)="onAgeFieldChange('maxAge')"
                  [disabled]="disabled"
                />
                <neo-dropdown
                  [options]="ageUnitOptions"
                  [(ngModel)]="maxAgeUnit"
                  (ngModelChange)="onAgeFieldChange('maxAge')"
                  [disabled]="disabled"
                ></neo-dropdown>
              </div>
            </div>
            <!-- Min Age: number + unit -->
            <div>
              <span class="block text-sm font-medium mb-1">Min Age</span>
              <div class="flex gap-1">
                <input
                  type="number"
                  min="0"
                  class="flex-1 w-0 px-3 py-2 bg-sys-bg border-2 border-sys-border shadow-neo-sm font-medium text-sm placeholder:text-sys-fg-tertiary focus:outline-none focus:ring-2 focus:ring-sys-accent-secondary disabled:opacity-50"
                  placeholder="0"
                  [(ngModel)]="minAgeNum"
                  (ngModelChange)="onAgeFieldChange('minAge')"
                  [disabled]="disabled"
                />
                <neo-dropdown
                  [options]="ageUnitOptions"
                  [(ngModel)]="minAgeUnit"
                  (ngModelChange)="onAgeFieldChange('minAge')"
                  [disabled]="disabled"
                ></neo-dropdown>
              </div>
            </div>
            <neo-input
              label="Max Depth"
              type="number"
              placeholder="empty = no limit"
              [(ngModel)]="config.maxDepth"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
            <neo-input
              label="Exclude If Present"
              placeholder="e.g. .nosync"
              [(ngModel)]="config.excludeIfPresent"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-input>
          </div>
          <div class="grid grid-cols-2 gap-3 mt-2">
            <neo-toggle
              [(ngModel)]="config.useRegex"
              (ngModelChange)="onConfigChange()"
              label="Use Regex"
              [disabled]="disabled"
            ></neo-toggle>
            <neo-toggle
              [(ngModel)]="config.deleteExcluded"
              (ngModelChange)="onConfigChange()"
              label="Delete Excluded"
              [disabled]="disabled"
            ></neo-toggle>
          </div>
        </details>
      </div>

      <!-- Safety -->
      <details>
        <summary class="text-sm font-bold flex items-center gap-2 cursor-pointer select-none">
          <i class="pi pi-shield"></i> Safety
        </summary>
        <div class="grid grid-cols-2 gap-3 mt-2">
          <neo-input
            label="Max Delete (%)"
            type="number"
            placeholder="100"
            [(ngModel)]="config.maxDelete"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
          <neo-input
            label="Max Transfer"
            placeholder="e.g. 10G"
            [(ngModel)]="config.maxTransfer"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
          <neo-input
            label="Max Delete Size"
            placeholder="e.g. 1G"
            [(ngModel)]="config.maxDeleteSize"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
          <neo-input
            label="Suffix"
            placeholder="e.g. .bak"
            [(ngModel)]="config.suffix"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
          <neo-input
            label="Backup Path"
            placeholder="path for backups"
            [(ngModel)]="config.backupPath"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-input>
        </div>
        <div class="grid grid-cols-2 gap-3 mt-2">
          <neo-toggle
            [(ngModel)]="config.immutable"
            (ngModelChange)="onConfigChange()"
            label="Immutable"
            [disabled]="disabled"
          ></neo-toggle>
          <neo-toggle
            [(ngModel)]="config.suffixKeepExtension"
            (ngModelChange)="onConfigChange()"
            label="Suffix Keep Extension"
            [disabled]="disabled"
          ></neo-toggle>
        </div>
      </details>

      <!-- Comparison -->
      <details>
        <summary class="text-sm font-bold flex items-center gap-2 cursor-pointer select-none">
          <i class="pi pi-check-circle"></i> Comparison
        </summary>
        <div class="grid grid-cols-3 gap-3 mt-2">
          <neo-toggle
            [(ngModel)]="config.sizeOnly"
            (ngModelChange)="onConfigChange()"
            label="Size Only"
            [disabled]="disabled"
          ></neo-toggle>
          <neo-toggle
            [(ngModel)]="config.updateMode"
            (ngModelChange)="onConfigChange()"
            label="Update (skip newer)"
            [disabled]="disabled"
          ></neo-toggle>
          <neo-toggle
            [(ngModel)]="config.ignoreExisting"
            (ngModelChange)="onConfigChange()"
            label="Ignore Existing"
            [disabled]="disabled"
          ></neo-toggle>
        </div>
      </details>

      <!-- Sync-specific (push/pull) -->
      @if (config.action === 'push' || config.action === 'pull') {
        <details>
          <summary class="text-sm font-bold flex items-center gap-2 cursor-pointer select-none">
            <i class="pi pi-sync"></i> Sync Options
          </summary>
          <div class="mt-2">
            <neo-dropdown
              label="Delete Timing"
              [options]="deleteTimingOptions"
              [fullWidth]="true"
              [(ngModel)]="config.deleteTiming"
              (ngModelChange)="onConfigChange()"
              [disabled]="disabled"
            ></neo-dropdown>
          </div>
        </details>
      }

      <!-- Bisync Options -->
      @if (config.action === 'bi' || config.action === 'bi-resync') {
        <div>
          <h3 class="text-sm font-bold mb-2 flex items-center gap-2">
            <i class="pi pi-arrows-h"></i> Bisync Options
          </h3>
          <neo-dropdown
            label="Conflict Resolution"
            [options]="conflictOptions"
            [fullWidth]="true"
            [(ngModel)]="config.conflictResolution"
            (ngModelChange)="onConfigChange()"
            [disabled]="disabled"
          ></neo-dropdown>
          <details class="mt-2">
            <summary class="text-xs text-sys-text-secondary cursor-pointer select-none hover:text-sys-text">Advanced Bisync</summary>
            <div class="grid grid-cols-2 gap-3 mt-2">
              <neo-dropdown
                label="Conflict Loser"
                [options]="conflictLoserOptions"
                [fullWidth]="true"
                [(ngModel)]="config.conflictLoser"
                (ngModelChange)="onConfigChange()"
                [disabled]="disabled"
              ></neo-dropdown>
              <neo-input
                label="Conflict Suffix"
                placeholder="e.g. .conflict"
                [(ngModel)]="config.conflictSuffix"
                (ngModelChange)="onConfigChange()"
                [disabled]="disabled"
              ></neo-input>
              <neo-input
                label="Max Lock"
                placeholder="e.g. 15m"
                [(ngModel)]="config.maxLock"
                (ngModelChange)="onConfigChange()"
                [disabled]="disabled"
              ></neo-input>
            </div>
            <div class="grid grid-cols-2 gap-3 mt-2">
              <neo-toggle
                [(ngModel)]="config.resilient"
                (ngModelChange)="onConfigChange()"
                label="Resilient"
                [disabled]="disabled"
              ></neo-toggle>
              <neo-toggle
                [(ngModel)]="config.checkAccess"
                (ngModelChange)="onConfigChange()"
                label="Check Access"
                [disabled]="disabled"
              ></neo-toggle>
            </div>
          </details>
        </div>
      }

      <!-- Schedule -->
      <div>
        <h3 class="text-sm font-bold mb-2 flex items-center gap-2">
          <i class="pi pi-clock"></i> Schedule
        </h3>
        <div class="flex items-center gap-4">
          <neo-toggle
            [(ngModel)]="scheduleEnabled"
            (ngModelChange)="onScheduleToggle()"
            label="Enable scheduling"
            [disabled]="disabled"
          ></neo-toggle>
          @if (scheduleEnabled) {
            <neo-input
              class="flex-1"
              placeholder="0 */6 * * * (every 6 hours)"
              [(ngModel)]="cronExpr"
              (ngModelChange)="onCronChange()"
              [disabled]="disabled"
            ></neo-input>
          }
        </div>
        @if (scheduleEnabled) {
          <div class="mt-2 flex gap-2 flex-wrap">
            @for (preset of cronPresets; track preset.value) {
              <neo-button
                variant="secondary"
                size="sm"
                (onClick)="setCronPreset(preset.value)"
                [disabled]="disabled"
              >
                {{ preset.label }}
              </neo-button>
            }
          </div>
        }
      </div>
    </div>
  `,
})
export class OperationSettingsPanelComponent implements OnInit {
  @Input() config: SyncConfig = { action: 'push' };
  @Input() scheduleEnabled = false;
  @Input() cronExpr = '';
  @Input() disabled = false;

  @Output() configChange = new EventEmitter<SyncConfig>();
  @Output() scheduleEnabledChange = new EventEmitter<boolean>();
  @Output() cronExprChange = new EventEmitter<string>();

  actionOptions: DropdownOption[] = [
    { value: 'push', label: 'Push', icon: 'pi pi-arrow-right', description: 'Source \u2192 Target. Deletes target files not in source.' },
    { value: 'pull', label: 'Pull', icon: 'pi pi-arrow-left', description: 'Target \u2192 Source. Deletes source files not in target.' },
    { value: 'bi', label: 'Bi-directional', icon: 'pi pi-arrows-h', description: 'Syncs both ways. Changes on either side propagate to the other.' },
    { value: 'bi-resync', label: 'Bi-directional (Resync)', icon: 'pi pi-refresh', description: 'Forces full re-sync. Use when sync state is lost or corrupted.' },
  ];

  conflictOptions: DropdownOption[] = [
    { value: 'newer', label: 'Keep newer file' },
    { value: 'older', label: 'Keep older file' },
    { value: 'larger', label: 'Keep larger file' },
    { value: 'smaller', label: 'Keep smaller file' },
    { value: 'path1', label: 'Keep source file' },
    { value: 'path2', label: 'Keep target file' },
  ];

  conflictLoserOptions: DropdownOption[] = [
    { value: 'delete', label: 'Delete' },
    { value: 'num', label: 'Number suffix' },
    { value: 'pathname', label: 'Path name suffix' },
  ];

  deleteTimingOptions: DropdownOption[] = [
    { value: '', label: 'Default (during)' },
    { value: 'before', label: 'Before sync' },
    { value: 'during', label: 'During sync' },
    { value: 'after', label: 'After sync' },
  ];

  cronPresets = [
    { label: 'Hourly', value: '0 * * * *' },
    { label: 'Every 6h', value: '0 */6 * * *' },
    { label: 'Daily', value: '0 0 * * *' },
    { label: 'Weekly', value: '0 0 * * 0' },
  ];

  sizeUnitOptions = [
    { value: 'k', label: 'KB' },
    { value: 'M', label: 'MB' },
    { value: 'G', label: 'GB' },
    { value: 'T', label: 'TB' },
  ];

  ageUnitOptions = [
    { value: 's', label: 'Sec' },
    { value: 'm', label: 'Min' },
    { value: 'h', label: 'Hour' },
    { value: 'd', label: 'Day' },
    { value: 'w', label: 'Week' },
    { value: 'M', label: 'Month' },
    { value: 'y', label: 'Year' },
  ];

  // Size/age split fields
  minSizeNum = '';
  minSizeUnit = 'M';
  maxSizeNum = '';
  maxSizeUnit = 'G';
  minAgeNum = '';
  minAgeUnit = 'h';
  maxAgeNum = '';
  maxAgeUnit = 'd';

  ngOnInit(): void {
    this.initSizeAgeFields();
  }

  get includedPathsText(): string {
    return this.config.includedPaths?.join('\n') || '';
  }

  get excludedPathsText(): string {
    return this.config.excludedPaths?.join('\n') || '';
  }

  updateIncludedPaths(text: string): void {
    this.config.includedPaths = text.split('\n').filter((p) => p.trim());
    this.onConfigChange();
  }

  updateExcludedPaths(text: string): void {
    this.config.excludedPaths = text.split('\n').filter((p) => p.trim());
    this.onConfigChange();
  }

  onConfigChange(): void {
    this.configChange.emit({ ...this.config });
  }

  onScheduleToggle(): void {
    this.scheduleEnabledChange.emit(this.scheduleEnabled);
  }

  onCronChange(): void {
    this.cronExprChange.emit(this.cronExpr);
  }

  setCronPreset(value: string): void {
    this.cronExpr = value;
    this.onCronChange();
  }

  onSizeFieldChange(field: 'minSize' | 'maxSize'): void {
    const num = field === 'minSize' ? this.minSizeNum : this.maxSizeNum;
    const unit = field === 'minSize' ? this.minSizeUnit : this.maxSizeUnit;
    this.config[field] = num ? `${num}${unit}` : '';
    this.onConfigChange();
  }

  onAgeFieldChange(field: 'minAge' | 'maxAge'): void {
    const num = field === 'minAge' ? this.minAgeNum : this.maxAgeNum;
    const unit = field === 'minAge' ? this.minAgeUnit : this.maxAgeUnit;
    this.config[field] = num ? `${num}${unit}` : '';
    this.onConfigChange();
  }

  private initSizeAgeFields(): void {
    const minSize = this.parseSizeValue(this.config.minSize);
    this.minSizeNum = minSize.num;
    this.minSizeUnit = minSize.unit;

    const maxSize = this.parseSizeValue(this.config.maxSize);
    this.maxSizeNum = maxSize.num;
    this.maxSizeUnit = maxSize.unit;

    const minAge = this.parseAgeValue(this.config.minAge);
    this.minAgeNum = minAge.num;
    this.minAgeUnit = minAge.unit;

    const maxAge = this.parseAgeValue(this.config.maxAge);
    this.maxAgeNum = maxAge.num;
    this.maxAgeUnit = maxAge.unit;
  }

  private parseSizeValue(val?: string): { num: string; unit: string } {
    if (!val) return { num: '', unit: 'M' };
    const match = val.match(/^(\d+\.?\d*)\s*([kMGT]?)$/i);
    if (!match) return { num: '', unit: 'M' };
    const unit = match[2];
    const normalized = unit.toLowerCase() === 'k' ? 'k' : unit.toUpperCase() || 'M';
    return { num: match[1], unit: normalized };
  }

  private parseAgeValue(val?: string): { num: string; unit: string } {
    if (!val) return { num: '', unit: 'h' };
    const match = val.match(/^(\d+\.?\d*)\s*([smhdwMy]?)$/);
    if (!match) return { num: '', unit: 'h' };
    return { num: match[1], unit: match[2] || 'h' };
  }
}

// frontend/src/components/flows/OperationSettingsPanel.vue
<script setup lang="ts">
/**
 * Wails `operation-settings-panel` port: Performance / Filtering / Safety /
 * Comparison / Sync|Bisync options for a flow operation.
 * Schedule stays on the flow card (not per-op).
 */
import { computed, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { PhPlus, PhX } from '@phosphor-icons/vue'
import { FLOW_ACTIONS, type FlowAction } from '@/constants/forms'
import {
  type SyncConfig,
  parseSyncConfig,
  serializeSyncConfig,
} from '@/lib/syncConfig'
import AppCheckbox from '@/components/ui/Checkbox.vue'
import CustomField from '@/components/forms/CustomField.vue'
import FieldUnit from '@/components/forms/FieldUnit.vue'

const props = withDefaults(
  defineProps<{
    /** Raw operation.sync_config */
    modelValue: Record<string, unknown> | null | undefined
    /** Column action fallback */
    action?: string
    disabled?: boolean
  }>(),
  { disabled: false },
)

const emit = defineEmits<{
  'update:modelValue': [value: Record<string, unknown>]
  /** When action changes, parent should sync op.action column */
  'update:action': [action: FlowAction]
}>()

const { t } = useI18n()

const cfg = ref<SyncConfig>(parseSyncConfig(props.modelValue, props.action || 'push'))

// Path list drafts
const includeDrafts = ref<string[]>([])
const excludeDrafts = ref<string[]>([])

// Size/age split UI
const minSizeNum = ref('')
const minSizeUnit = ref('M')
const maxSizeNum = ref('')
const maxSizeUnit = ref('G')
const minAgeNum = ref('')
const minAgeUnit = ref('h')
const maxAgeNum = ref('')
const maxAgeUnit = ref('d')

const sizeUnits = [
  { value: 'k', label: 'KB' },
  { value: 'M', label: 'MB' },
  { value: 'G', label: 'GB' },
  { value: 'T', label: 'TB' },
]
const ageUnits = [
  { value: 's', label: 's' },
  { value: 'm', label: 'm' },
  { value: 'h', label: 'h' },
  { value: 'd', label: 'd' },
  { value: 'w', label: 'w' },
  { value: 'M', label: 'M' },
  { value: 'y', label: 'y' },
]

const conflictOptions = [
  { value: 'newer', labelKey: 'workspace.opSettings.conflictNewer' },
  { value: 'older', labelKey: 'workspace.opSettings.conflictOlder' },
  { value: 'larger', labelKey: 'workspace.opSettings.conflictLarger' },
  { value: 'smaller', labelKey: 'workspace.opSettings.conflictSmaller' },
  { value: 'path1', labelKey: 'workspace.opSettings.conflictSource' },
  { value: 'path2', labelKey: 'workspace.opSettings.conflictTarget' },
]
const conflictLoserOptions = [
  { value: 'delete', labelKey: 'workspace.opSettings.loserDelete' },
  { value: 'num', labelKey: 'workspace.opSettings.loserNum' },
  { value: 'pathname', labelKey: 'workspace.opSettings.loserPath' },
]
const deleteTimingOptions = [
  { value: '', labelKey: 'workspace.opSettings.deleteDefault' },
  { value: 'before', labelKey: 'workspace.opSettings.deleteBefore' },
  { value: 'during', labelKey: 'workspace.opSettings.deleteDuring' },
  { value: 'after', labelKey: 'workspace.opSettings.deleteAfter' },
]

const isBi = computed(
  () => cfg.value.action === 'bi' || cfg.value.action === 'bi-resync',
)
const isPush = computed(() => cfg.value.action === 'push')

const actionOptions = computed(() =>
  FLOW_ACTIONS.map((a) => ({ value: a, label: t(`workspace.actionOptions.${a}`) })),
)
const conflictOptionList = computed(() => [
  { value: '', label: t('common.select') },
  ...conflictOptions.map((o) => ({ value: o.value, label: t(o.labelKey) })),
])
const conflictLoserOptionList = computed(() => [
  { value: '', label: t('common.select') },
  ...conflictLoserOptions.map((o) => ({ value: o.value, label: t(o.labelKey) })),
])
const deleteTimingOptionList = computed(() =>
  deleteTimingOptions.map((o) => ({ value: o.value, label: t(o.labelKey) })),
)

function splitSizeAge(val: string | undefined): { n: string; u: string } {
  if (!val) return { n: '', u: 'M' }
  const m = /^([0-9.]+)\s*([a-zA-Z]+)?$/.exec(val.trim())
  if (!m) return { n: val, u: 'M' }
  return { n: m[1], u: m[2] || 'M' }
}

function joinSizeAge(n: string, u: string): string | undefined {
  const t = n.trim()
  if (!t || Number(t) === 0) return undefined
  return `${t}${u}`
}

function hydrateFromProps() {
  cfg.value = parseSyncConfig(props.modelValue, props.action || 'push')
  includeDrafts.value = [...(cfg.value.includedPaths ?? [])]
  excludeDrafts.value = [...(cfg.value.excludedPaths ?? [])]
  const minS = splitSizeAge(cfg.value.minSize)
  minSizeNum.value = minS.n
  minSizeUnit.value = minS.u === 'k' || minS.u === 'M' || minS.u === 'G' || minS.u === 'T' ? minS.u : 'M'
  const maxS = splitSizeAge(cfg.value.maxSize)
  maxSizeNum.value = maxS.n
  maxSizeUnit.value = maxS.u === 'k' || maxS.u === 'M' || maxS.u === 'G' || maxS.u === 'T' ? maxS.u : 'G'
  const minA = splitSizeAge(cfg.value.minAge)
  minAgeNum.value = minA.n
  minAgeUnit.value = minA.u || 'h'
  const maxA = splitSizeAge(cfg.value.maxAge)
  maxAgeNum.value = maxA.n
  maxAgeUnit.value = maxA.u || 'd'
}

watch(
  () => [props.modelValue, props.action] as const,
  () => hydrateFromProps(),
  { immediate: true, deep: true },
)

function emitConfig() {
  cfg.value.minSize = joinSizeAge(minSizeNum.value, minSizeUnit.value)
  cfg.value.maxSize = joinSizeAge(maxSizeNum.value, maxSizeUnit.value)
  cfg.value.minAge = joinSizeAge(minAgeNum.value, minAgeUnit.value)
  cfg.value.maxAge = joinSizeAge(maxAgeNum.value, maxAgeUnit.value)
  cfg.value.includedPaths = includeDrafts.value.map((s) => s.trim()).filter(Boolean)
  cfg.value.excludedPaths = excludeDrafts.value.map((s) => s.trim()).filter(Boolean)
  const serialized = serializeSyncConfig(cfg.value)
  emit('update:modelValue', serialized)
  emit('update:action', cfg.value.action)
}

function setAction(a: string) {
  cfg.value.action = a as FlowAction
  emitConfig()
}

function patchNum(key: keyof SyncConfig, raw: string) {
  const bag = cfg.value as unknown as Record<string, unknown>
  const t = raw.trim()
  if (t === '') {
    delete bag[key as string]
  } else {
    const n = Number(t)
    if (!Number.isNaN(n)) bag[key as string] = n
  }
  emitConfig()
}

function patchStr(key: keyof SyncConfig, raw: string) {
  const bag = cfg.value as unknown as Record<string, unknown>
  const t = raw.trim()
  if (t === '') delete bag[key as string]
  else bag[key as string] = t
  emitConfig()
}

function patchBool(key: keyof SyncConfig, v: boolean) {
  const bag = cfg.value as unknown as Record<string, unknown>
  bag[key as string] = v
  emitConfig()
}

function addInclude() {
  includeDrafts.value = [...includeDrafts.value, '']
}
function addExclude() {
  excludeDrafts.value = [...excludeDrafts.value, '']
}
function removeInclude(i: number) {
  includeDrafts.value = includeDrafts.value.filter((_, idx) => idx !== i)
  emitConfig()
}
function removeExclude(i: number) {
  excludeDrafts.value = excludeDrafts.value.filter((_, idx) => idx !== i)
  emitConfig()
}
</script>

<template>
  <div
    class="space-y-3 border-t border-border bg-bg p-3"
    :class="disabled && 'pointer-events-none'"
    :aria-disabled="disabled"
    data-testid="op-settings-panel"
  >
    <!-- Action + Dry run -->
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:items-end">
      <CustomField
        kind="select"
        :model-value="cfg.action"
        :label="t('workspace.action')"
        :options="actionOptions"
        :disabled="disabled"
        :help="t(`workspace.actionHelp.${cfg.action}`)"
        test-id="op-settings-action"
        @change="setAction($event)"
      />
      <div class="flex items-end pb-1">
        <AppCheckbox
          :model-value="!!cfg.dryRun"
          :disabled="disabled"
          :label="t('workspace.dryRun')"
          test-id="op-settings-dry-run"
          @update:model-value="patchBool('dryRun', !!$event)"
        />
      </div>
    </div>

    <!-- Performance -->
    <section class="rounded-md border border-border">
      <header
        class="flex items-center gap-2 border-b border-border border-l-4 border-l-[var(--color-info,#5ca8e8)] bg-bg-secondary px-3 py-2 text-xs font-semibold uppercase tracking-wide"
      >
        {{ t('workspace.opSettings.performance') }}
      </header>
      <div class="space-y-3 p-3">
        <div class="grid grid-cols-2 gap-2">
          <CustomField
            :model-value="cfg.parallel ?? ''"
            :label="t('workspace.opSettings.parallel')"
            type="number"
            :min="0"
            placeholder="8"
            :disabled="disabled"
            @change="patchNum('parallel', $event)"
          />
          <CustomField
            :model-value="cfg.bandwidth ?? ''"
            :label="t('workspace.opSettings.bandwidth')"
            type="number"
            :min="0"
            placeholder="0"
            :disabled="disabled"
            @change="patchNum('bandwidth', $event)"
          />
        </div>
        <div class="border-t border-border pt-3">
          <div class="mb-2 text-xs font-bold uppercase tracking-wide text-text-muted">
            {{ t('workspace.opSettings.advanced') }}
          </div>
          <div class="grid grid-cols-2 gap-2">
            <CustomField
              :model-value="cfg.multiThreadStreams ?? ''"
              :label="t('workspace.opSettings.multiThread')"
              type="number"
              :disabled="disabled"
              @change="patchNum('multiThreadStreams', $event)"
            />
            <CustomField
              :model-value="cfg.bufferSize ?? ''"
              :label="t('workspace.opSettings.bufferSize')"
              placeholder="16M"
              :disabled="disabled"
              @change="patchStr('bufferSize', $event)"
            />
            <CustomField
              :model-value="cfg.retries ?? ''"
              :label="t('workspace.opSettings.retries')"
              type="number"
              :disabled="disabled"
              @change="patchNum('retries', $event)"
            />
            <CustomField
              :model-value="cfg.lowLevelRetries ?? ''"
              :label="t('workspace.opSettings.lowLevelRetries')"
              type="number"
              :disabled="disabled"
              @change="patchNum('lowLevelRetries', $event)"
            />
            <CustomField
              :model-value="cfg.maxDuration ?? ''"
              :label="t('workspace.opSettings.maxDuration')"
              placeholder="1h30m"
              :disabled="disabled"
              @change="patchStr('maxDuration', $event)"
            />
            <CustomField
              :model-value="cfg.retriesSleep ?? ''"
              :label="t('workspace.opSettings.retriesSleep')"
              placeholder="10s"
              :disabled="disabled"
              @change="patchStr('retriesSleep', $event)"
            />
            <CustomField
              :model-value="cfg.tpsLimit ?? ''"
              :label="t('workspace.opSettings.tpsLimit')"
              type="number"
              :disabled="disabled"
              @change="patchNum('tpsLimit', $event)"
            />
            <CustomField
              :model-value="cfg.connTimeout ?? ''"
              :label="t('workspace.opSettings.connTimeout')"
              placeholder="30s"
              :disabled="disabled"
              @change="patchStr('connTimeout', $event)"
            />
            <CustomField
              :model-value="cfg.ioTimeout ?? ''"
              :label="t('workspace.opSettings.ioTimeout')"
              placeholder="5m"
              :disabled="disabled"
              @change="patchStr('ioTimeout', $event)"
            />
            <CustomField
              :model-value="cfg.orderBy ?? ''"
              :label="t('workspace.opSettings.orderBy')"
              placeholder="size,desc"
              :disabled="disabled"
              @change="patchStr('orderBy', $event)"
            />
          </div>
          <div class="mt-2">
            <AppCheckbox
              :model-value="!!cfg.checkFirst"
              :disabled="disabled"
              :label="t('workspace.opSettings.checkFirst')"
              @update:model-value="patchBool('checkFirst', !!$event)"
            />
          </div>
        </div>
      </div>
    </section>

    <!-- Filtering -->
    <section class="rounded-md border border-border">
      <header
        class="flex items-center gap-2 border-b border-border border-l-4 border-l-[var(--color-accent-strong,#6ee7df)] bg-bg-secondary px-3 py-2 text-xs font-semibold uppercase tracking-wide"
      >
        {{ t('workspace.opSettings.filtering') }}
      </header>
      <div class="space-y-3 p-3">
        <div>
          <div class="mb-1 text-xs font-bold text-text-muted">{{ t('workspace.opSettings.includePaths') }}</div>
          <div
            v-for="(row, i) in includeDrafts"
            :key="`inc-${i}`"
            class="mb-1 flex items-center gap-2"
          >
            <CustomField
              class="min-w-0 flex-1"
              :model-value="includeDrafts[i]"
              placeholder="/path or *.ext"
              mono
              :disabled="disabled"
              @input="includeDrafts[i] = $event"
              @change="emitConfig"
            />
            <button type="button" class="btn-ghost !px-1" :disabled="disabled" @click="removeInclude(i)">
              <PhX :size="12" class="text-danger" />
            </button>
          </div>
          <button
            type="button"
            class="text-xs text-text-muted hover:text-text disabled:cursor-not-allowed disabled:text-text-dim disabled:opacity-60"
            :disabled="disabled"
            @click="addInclude"
          >
            <PhPlus :size="12" class="mr-0.5 inline" /> {{ t('workspace.opSettings.addPath') }}
          </button>
        </div>
        <div>
          <div class="mb-1 text-xs font-bold text-text-muted">{{ t('workspace.opSettings.excludePaths') }}</div>
          <div
            v-for="(row, i) in excludeDrafts"
            :key="`exc-${i}`"
            class="mb-1 flex items-center gap-2"
          >
            <CustomField
              class="min-w-0 flex-1"
              :model-value="excludeDrafts[i]"
              placeholder="*.tmp or node_modules/"
              mono
              :disabled="disabled"
              @input="excludeDrafts[i] = $event"
              @change="emitConfig"
            />
            <button type="button" class="btn-ghost !px-1" :disabled="disabled" @click="removeExclude(i)">
              <PhX :size="12" class="text-danger" />
            </button>
          </div>
          <button
            type="button"
            class="text-xs text-text-muted hover:text-text disabled:cursor-not-allowed disabled:text-text-dim disabled:opacity-60"
            :disabled="disabled"
            @click="addExclude"
          >
            <PhPlus :size="12" class="mr-0.5 inline" /> {{ t('workspace.opSettings.addPath') }}
          </button>
        </div>
        <div class="border-t border-border pt-3">
          <div class="mb-2 text-xs font-bold uppercase tracking-wide text-text-muted">
            {{ t('workspace.opSettings.advanced') }}
          </div>
          <div class="grid grid-cols-2 gap-2">
            <FieldUnit
              :label="t('workspace.opSettings.minSize')"
              :model-value="minSizeNum"
              :unit-value="minSizeUnit"
              :units="sizeUnits"
              :disabled="disabled"
              @input="minSizeNum = $event"
              @change="emitConfig"
              @change-unit="minSizeUnit = $event; emitConfig()"
            />
            <FieldUnit
              :label="t('workspace.opSettings.maxSize')"
              :model-value="maxSizeNum"
              :unit-value="maxSizeUnit"
              :units="sizeUnits"
              :disabled="disabled"
              @input="maxSizeNum = $event"
              @change="emitConfig"
              @change-unit="maxSizeUnit = $event; emitConfig()"
            />
            <FieldUnit
              :label="t('workspace.opSettings.maxAge')"
              :model-value="maxAgeNum"
              :unit-value="maxAgeUnit"
              :units="ageUnits"
              :disabled="disabled"
              @input="maxAgeNum = $event"
              @change="emitConfig"
              @change-unit="maxAgeUnit = $event; emitConfig()"
            />
            <FieldUnit
              :label="t('workspace.opSettings.minAge')"
              :model-value="minAgeNum"
              :unit-value="minAgeUnit"
              :units="ageUnits"
              :disabled="disabled"
              @input="minAgeNum = $event"
              @change="emitConfig"
              @change-unit="minAgeUnit = $event; emitConfig()"
            />
            <CustomField
              :model-value="cfg.maxDepth ?? ''"
              :label="t('workspace.opSettings.maxDepth')"
              type="number"
              :disabled="disabled"
              @change="patchNum('maxDepth', $event)"
            />
            <CustomField
              :model-value="cfg.excludeIfPresent ?? ''"
              :label="t('workspace.opSettings.excludeIfPresent')"
              placeholder=".nosync"
              :disabled="disabled"
              @change="patchStr('excludeIfPresent', $event)"
            />
          </div>
          <div class="mt-2 flex flex-wrap gap-4">
            <AppCheckbox
              :model-value="!!cfg.useRegex"
              :disabled="disabled"
              :label="t('workspace.opSettings.useRegex')"
              @update:model-value="patchBool('useRegex', !!$event)"
            />
            <AppCheckbox
              :model-value="!!cfg.deleteExcluded"
              :disabled="disabled"
              :label="t('workspace.opSettings.deleteExcluded')"
              @update:model-value="patchBool('deleteExcluded', !!$event)"
            />
          </div>
        </div>
      </div>
    </section>

    <!-- Safety -->
    <section class="rounded-md border border-border">
      <header
        class="flex items-center gap-2 border-b border-border border-l-4 border-l-[var(--color-warning,#e7b866)] bg-bg-secondary px-3 py-2 text-xs font-semibold uppercase tracking-wide"
      >
        {{ t('workspace.opSettings.safety') }}
      </header>
      <div class="space-y-3 p-3">
        <div class="grid grid-cols-2 gap-2">
          <CustomField
            :model-value="cfg.maxDelete ?? ''"
            :label="t('workspace.opSettings.maxDelete')"
            type="number"
            placeholder="100"
            :disabled="disabled"
            @change="patchNum('maxDelete', $event)"
          />
          <CustomField
            :model-value="cfg.maxTransfer ?? ''"
            :label="t('workspace.opSettings.maxTransfer')"
            placeholder="10G"
            :disabled="disabled"
            @change="patchStr('maxTransfer', $event)"
          />
          <CustomField
            :model-value="cfg.maxDeleteSize ?? ''"
            :label="t('workspace.opSettings.maxDeleteSize')"
            placeholder="1G"
            :disabled="disabled"
            @change="patchStr('maxDeleteSize', $event)"
          />
          <CustomField
            :model-value="cfg.suffix ?? ''"
            :label="t('workspace.opSettings.suffix')"
            placeholder=".bak"
            :disabled="disabled"
            @change="patchStr('suffix', $event)"
          />
          <CustomField
            class="sm:col-span-2"
            :model-value="cfg.backupPath ?? ''"
            :label="t('workspace.opSettings.backupPath')"
            :disabled="disabled"
            @change="patchStr('backupPath', $event)"
          />
        </div>
        <div class="flex flex-wrap gap-4">
          <AppCheckbox
            :model-value="!!cfg.immutable"
            :disabled="disabled"
            :label="t('workspace.opSettings.immutable')"
            @update:model-value="patchBool('immutable', !!$event)"
          />
          <AppCheckbox
            :model-value="!!cfg.suffixKeepExtension"
            :disabled="disabled"
            :label="t('workspace.opSettings.suffixKeepExt')"
            @update:model-value="patchBool('suffixKeepExtension', !!$event)"
          />
        </div>
      </div>
    </section>

    <!-- Comparison -->
    <section class="rounded-md border border-border">
      <header
        class="flex items-center gap-2 border-b border-border border-l-4 border-l-[var(--color-success,#5cc786)] bg-bg-secondary px-3 py-2 text-xs font-semibold uppercase tracking-wide"
      >
        {{ t('workspace.opSettings.comparison') }}
      </header>
      <div class="flex flex-wrap gap-4 p-3">
        <AppCheckbox
          :model-value="!!cfg.sizeOnly"
          :disabled="disabled"
          :label="t('workspace.opSettings.sizeOnly')"
          @update:model-value="patchBool('sizeOnly', !!$event)"
        />
        <AppCheckbox
          :model-value="!!cfg.updateMode"
          :disabled="disabled"
          :label="t('workspace.opSettings.updateMode')"
          @update:model-value="patchBool('updateMode', !!$event)"
        />
        <AppCheckbox
          :model-value="!!cfg.ignoreExisting"
          :disabled="disabled"
          :label="t('workspace.opSettings.ignoreExisting')"
          @update:model-value="patchBool('ignoreExisting', !!$event)"
        />
      </div>
    </section>

    <!-- Sync options (push) -->
    <section v-if="isPush" class="rounded-md border border-border">
      <header
        class="flex items-center gap-2 border-b border-border border-l-4 border-l-[var(--color-info,#5ca8e8)] bg-bg-secondary px-3 py-2 text-xs font-semibold uppercase tracking-wide"
      >
        {{ t('workspace.opSettings.syncOptions') }}
      </header>
      <div class="p-3">
        <CustomField
          kind="select"
          :model-value="cfg.deleteTiming ?? ''"
          :label="t('workspace.opSettings.deleteTiming')"
          :options="deleteTimingOptionList"
          :disabled="disabled"
          @change="patchStr('deleteTiming', $event)"
        />
      </div>
    </section>

    <!-- Bisync options -->
    <section v-if="isBi" class="rounded-md border border-border">
      <header
        class="flex items-center gap-2 border-b border-border border-l-4 border-l-[var(--color-danger,#eb6b6f)] bg-bg-secondary px-3 py-2 text-xs font-semibold uppercase tracking-wide"
      >
        {{ t('workspace.opSettings.bisyncOptions') }}
      </header>
      <div class="space-y-3 p-3">
        <CustomField
          kind="select"
          :model-value="cfg.conflictResolution ?? ''"
          :label="t('workspace.opSettings.conflictResolution')"
          :options="conflictOptionList"
          :disabled="disabled"
          @change="patchStr('conflictResolution', $event)"
        />
        <div class="border-t border-border pt-3">
          <div class="mb-2 text-xs font-bold uppercase tracking-wide text-text-muted">
            {{ t('workspace.opSettings.advanced') }}
          </div>
          <div class="grid grid-cols-2 gap-2">
            <CustomField
              kind="select"
              :model-value="cfg.conflictLoser ?? ''"
              :label="t('workspace.opSettings.conflictLoser')"
              :options="conflictLoserOptionList"
              :disabled="disabled"
              @change="patchStr('conflictLoser', $event)"
            />
            <CustomField
              :model-value="cfg.conflictSuffix ?? ''"
              :label="t('workspace.opSettings.conflictSuffix')"
              :disabled="disabled"
              @change="patchStr('conflictSuffix', $event)"
            />
            <CustomField
              :model-value="cfg.maxLock ?? ''"
              :label="t('workspace.opSettings.maxLock')"
              placeholder="15m"
              :disabled="disabled"
              @change="patchStr('maxLock', $event)"
            />
          </div>
          <div class="mt-2 flex flex-wrap gap-4">
            <AppCheckbox
              :model-value="!!cfg.resilient"
              :disabled="disabled"
              :label="t('workspace.opSettings.resilient')"
              @update:model-value="patchBool('resilient', !!$event)"
            />
            <AppCheckbox
              :model-value="!!cfg.checkAccess"
              :disabled="disabled"
              :label="t('workspace.opSettings.checkAccess')"
              @update:model-value="patchBool('checkAccess', !!$event)"
            />
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
